### PR TITLE
SPARK-36429: Add ociImageUrl property

### PR DESCRIPTION
**Pull request by den314**
* add ociImageUrl property to AS3 interface
* add oci_image_url DB column
* add maintainer code to STB interface

### CODE REVIEW

**Comment by djasiok** [comment]
run build

**Review by djasiok — APPROVED** [review]

**Review by AnDyXX — APPROVED** [review]

**Comment by den314** [comment]
run build

**Review by alewir — APPROVED** [review]

**Comment by djasiok** [comment]
run build

**Comment by den314** [comment]
run build

**Comment by djasiok** [comment]
run build

**Comment by djasiok** [comment]
run build

**Pull request merged**
